# Generated by Django 3.1.4 on 2020-12-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('link', models.URLField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(blank=True)),
                ('crdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
