# Generated by Django 3.1.4 on 2020-12-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201226_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='user_id',
        ),
    ]
