# Generated by Django 3.1.4 on 2020-12-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201226_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user_id',
            new_name='user',
        ),
    ]
